/** Auto-generated by vue-nnn-router — do not edit */
import type { NnnScrollMap } from "vue-nnn-router";

export const NNN_SCROLL: NnnScrollMap = {
  "src/pages/child.vue": {"restorePosition":true},

};
