/** Auto-generated by vue-nnn-router — do not edit */
export const ROUTER_NAME = {
  child: "child",
  home: "home",
  messages: "messages",
  notifications: "notifications",
  profile: "profile",

} as const;

export type RouterName = (typeof ROUTER_NAME)[keyof typeof ROUTER_NAME];
